stages:
  - docker-build
  - doc-build
  - doc-deploy
  - build
  - test
 
job2:
  stage: build
  #allow_failure: false
  script:
    - echo "bonjour"
  only:
    - master

job3:
  stage: test
  #allow_failure: false
  script:
    - echo "bonjour"
  dependencies: [job2]
  only:
    - master

