# Templates for ci jobs
include: 
  - ci_gitlab/gitlab-ci-siconos-templates.yml
  #- template: Code-Quality.gitlab-ci.yml


# full:ubuntu18.04:
#      variables:
#        IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu18.04
#        cdash_submit: 1
#        user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
#      extends: .siconos-full

ubuntu18.04:
  stage: configure
  trigger:
    include:
      - ci_gitlab/ubuntu.yml

debianbuster:
  stage: configure
  trigger:
    include:
      - ci_gitlab/debianbuster.yml
