# Templates for ci jobs
include: ci_gitlab/gitlab-ci-siconos-templates.yml

job2:
  stage: build
  #allow_failure: false
  script:
    - echo "bonjour"
  only:
    - master

job3:
  stage: test
  #allow_failure: false
  script:
    - echo "bonjour"
  dependencies: [job2]
  only:
    - master

# ---- Siconos build jobs -----

metrics:
  image: $CI_REGISTRY_IMAGE/ubuntu18.04
  stage: docker-build
  script:
    - echo 'metric_name metric_value' > metrics.txt
  artifacts:
    reports:
      metrics: metrics.txt

run_rats:
  image: $CI_REGISTRY_IMAGE/ubuntu18.04
  stage: docker-build
  type: test
  script:
  -  apt update  && apt install -y -qq wget
  - wget http://downloads.sourceforge.net/project/expat/expat/2.0.1/expat-2.0.1.tar.gz
  - tar -xvf expat-2.0.1.tar.gz
  - cd expat-2.0.1 && ./configure && make && make install
  - wget https://rough-auditing-tool-for-security.googlecode.com/files/rats-2.4.tgz
  - tar -xzvf rats-2.4.tgz
  - cd rats-2.4 && ./configure && make && sudo make install
  - rats -l 'c' ./kernel/src/modelingTools/* >> rats.txt
  - test $(grep -c 'High' rats.txt) -eq 0
  artifacts:
    when: always
    untracked: true
    paths:
    - ./kernel/src/modelingTools/*
    - ./.gitlab-ci.yml


# Siconos build and install, default config
# (based on cmake/default_siconos.cmake)
# on ubuntu 18.04.
configure:ubuntu18.04:
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu18.04
    cdash_submit: 1
    user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
  extends: .siconos-configure
  artifacts:
    paths:
      - $CI_PROJECT_DIR
    when: always
    reports:
      junit: $CI_PROJECT_DIR/build/Testing/my-cunit-test.xml

build:ubuntu18.04:
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu18.04
    cdash_submit: 1
    user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
  extends: .siconos-build
  artifacts:
    paths:
      - $CI_PROJECT_DIR

test:ubuntu18.04:
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu18.04
    cdash_submit: 1
    user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
  extends: .siconos-test
  artifacts:
    paths:
      - build

