# Templates for ci jobs
include: 
  - ci_gitlab/gitlab-ci-siconos-templates.yml
  #- template: Code-Quality.gitlab-ci.yml

#job2:
#  stage: build
#  #allow_failure: false
#  script:
#    - echo "bonjour"
#  only:
#    - master

#job3:
#  stage: test
#  #allow_failure: false
#  script:
#    - echo "bonjour"
#  dependencies: [job2]
#  only:
#    - master

# ---- Siconos build jobs -----

metrics:
  image: $CI_REGISTRY_IMAGE/ubuntu18.04
  stage: docker-build
  script:
    - echo 'metric_name metric_value' > metrics.txt
  artifacts:
    reports:
      metrics: metrics.txt


#code_quality:
#  stage: test
#  artifacts:
#    paths: [gl-code-quality-report.json]
    
# Siconos build and install, default config
# (based on cmake/default_siconos.cmake)
# on ubuntu 18.04.
configure:ubuntu18.04:
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu18.04
    cdash_submit: 1
    user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
  extends: .siconos-configure
  when : manual
  artifacts:
    paths:
      - $CI_PROJECT_DIR
    #when: always
    #reports:
    #  junit: $CI_PROJECT_DIR/build/Testing/Build.xml

build:ubuntu18.04:
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu18.04
    cdash_submit: 1
    user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
    GIT_STRATEGY: none
  extends: .siconos-build
  dependencies: configure:ubuntu18.04
  artifacts:
    paths:
      - $CI_PROJECT_DIR

test:ubuntu18.04:
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu18.04
    cdash_submit: 1
    user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
    GIT_STRATEGY: none
  dependencies: build:ubuntu18.04
  extends: .siconos-test
  artifacts:
    paths:
      - build

