# Templates for ci jobs
include: 
  - ci_gitlab/gitlab-ci-siconos-templates.yml
  #- template: Code-Quality.gitlab-ci.yml


# full:ubuntu18.04:
#      variables:
#        IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu18.04
#        cdash_submit: 1
#        user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
#      extends: .siconos-full

# full:ubuntu18.04:
#       variables:
#         IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu18.04
#         cdash_submit: 1
#         user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
#       extends: .siconos-full
      
configure:debian-buster:
   variables:
     IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
     cdash_submit: 1
     user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
   extends: .siconos-configure

build:debian-buster:
    variables:
      IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
      cdash_submit: 1
      user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
    extends: .siconos-build
    needs: ["configure:debian-buster"]

test:debian-buster:
    variables:
      IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
      cdash_submit: 1
      user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
    needs: ["build:debian-buster"]
    extends: .siconos-test

configure:essai:
   variables:
     IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
     cdash_submit: 1
     user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_try.cmake
   extends: .siconos-configure

build:essai:
    variables:
      IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
      cdash_submit: 1
      user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_try.cmake
    extends: .siconos-build
    needs: ["configure:essai"]

test:essai:
    variables:
      IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
      cdash_submit: 1
      user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_try.cmake
    extends: .siconos-test
    needs: ["build:essai"]
# ubuntu18.04:
#   stage: configure
#   trigger:
#     include:
#       - ci_gitlab/ubuntu.yml

# debianbuster:
#   stage: configure
#   trigger:
#     include:
#       - ci_gitlab/debianbuster.yml
