# Templates for ci jobs - test cdash
include: 
  - ci_gitlab/gitlab-ci-siconos-templates.yml
  #- template: Code-Quality.gitlab-ci.yml

# test workflow aaa
workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /-wip$/
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /AARG$/
      when: never
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'
      when: never
    - when: always

docker-build:debian-buster:
  variables:
    IMAGE_NAME: debian-buster
  extends: .docker-build

ubuntu18.04:full:
      variables:
        IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu18.04
        cdash_submit: 1
        user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
      extends: .siconos-full
      
debian-buster:configure:
   variables:
     IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
     cdash_submit: 1
     user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
   extends: .siconos-configure

debian-buster:build:
    variables:
      IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
      cdash_submit: 1
      user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
    extends: .siconos-build
    needs: ["debian-buster:configure"]

debian-buster:test:
    variables:
      IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
      cdash_submit: 1
      user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
    needs: ["debian-buster:build"]
    extends: .siconos-test

essai:configure:
   variables:
     IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
     cdash_submit: 1
     user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_try.cmake
   extends: .siconos-configure

essai:build:
    variables:
      IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
      cdash_submit: 1
      user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_try.cmake
    extends: .siconos-build
    needs: ["essai:configure"]

essai:test:
    variables:
      IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
      cdash_submit: 1
      user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_try.cmake
    extends: .siconos-test
    needs: ["essai:build"]

# Try to generate sico install
#debianbuster:install:
#  variables:
#    siconos_docker_name: siconos-$CI_COMMIT_REF_NAME-debian-buster
#  extends: .siconos-install
#  needs: ["debian-buster:build"]


debianbuster:install:
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
    siconos_docker_name: siconos-$CI_COMMIT_REF_NAME-debian-buster
  #allow_failure: true
  extends: .siconos-install
  needs: ["debian-buster:build"]

ubuntu18:install:
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu18.04
    siconos_docker_name: siconos-$CI_COMMIT_REF_NAME-ubuntu-bionic
  extends: .siconos-install
  needs: ["ubuntu18.04:full"]

# ubuntu18.04:
#   stage: configure
#   trigger:
#     include:
#       - ci_gitlab/ubuntu.yml

# debianbuster:
#   stage: configure
#   trigger:
#     include:
#       - ci_gitlab/debianbuster.yml
