# Templates for ci jobs - test cdash
include: 
  - ci_gitlab/gitlab-ci-siconos-templates.yml
  #- template: Code-Quality.gitlab-ci.yml

# test workflow
workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /-wip$/
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /AARG$/
      when: never
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'
      when: never
    - when: always

# --- First, build docker images that contains all the required dependencies to build siconos ---
# This step is optional and run only when the commit message starts with "[docker-build]"
docker-build:debian-buster:
  variables:
    IMAGE_NAME: debian-buster
  extends: .docker-build

docker-build:debian-stretch:
  variables:
    IMAGE_NAME: debian-stretch
  extends: .docker-build

docker-build:ubuntu20.4-no-python:
  variables:
    IMAGE_NAME: ubuntu20.04-no-python
  extends: .docker-build

docker-build:ubuntu20.4:
  variables:
    IMAGE_NAME: ubuntu20.04
  extends: .docker-build

docker-build:ubuntu18.04:
  variables:
    IMAGE_NAME: ubuntu18.04
  extends: .docker-build

docker-build:opensuse-leap-15.0:
  variables:
    IMAGE_NAME: opensuse-leap-15.0
  extends: .docker-build

docker-build:archlinux-oce:
  variables:
    IMAGE_NAME: archlinux-oce
  extends: .docker-build
  when: manual

docker-build:centos-7:
  variables:
    IMAGE_NAME: centos-7
  extends: .docker-build

docker-build:fedora33:
  variables:
    IMAGE_NAME: fedora-33
  extends: .docker-build


ubuntu18.04:full:
      variables:
        IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu18.04
        cdash_submit: 1
        user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
      extends: .siconos-full
      
debian-buster:configure:
   variables:
     IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
     cdash_submit: 1
     user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
   extends: .siconos-configure

debian-buster:build:
    variables:
      IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
      cdash_submit: 1
      user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
    extends: .siconos-build
    needs: ["debian-buster:configure"]

debian-buster:test:
    variables:
      IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
      cdash_submit: 1
      user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
    needs: ["debian-buster:build"]
    extends: .siconos-test

ubuntu20.04:configure:
   variables:
     IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu20.04
     cdash_submit: 1
     user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
   extends: .siconos-configure

ubuntu20.04:build:
    variables:
      IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu20.04
      cdash_submit: 1
      user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
    extends: .siconos-build
    needs: ["ubuntu20.04:configure"]

ubuntu20.04:test:
    variables:
      IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu20.04
      cdash_submit: 1
      user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
    needs: ["ubuntu20.04:build"]
    extends: .siconos-test

# essai:configure:
#    variables:
#      IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
#      cdash_submit: 1
#      user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_try.cmake
#    extends: .siconos-configure

# essai:build:
#     variables:
#       IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
#       cdash_submit: 1
#       user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_try.cmake
#     extends: .siconos-build
#     needs: ["essai:configure"]

# essai:test:
#     variables:
#       IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
#       cdash_submit: 1
#       user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_try.cmake
#     extends: .siconos-test
#     needs: ["essai:build"]

# Try to generate sico install
#debianbuster:install:
#  variables:
#    siconos_docker_name: siconos-$CI_COMMIT_REF_NAME-debian-buster
#  extends: .siconos-install
#  needs: ["debian-buster:build"]


debianbuster:install:
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/debian-buster
    siconos_docker_name: siconos-$CI_COMMIT_REF_NAME-debian-buster
  #allow_failure: true
  extends: .siconos-install
  needs: ["debian-buster:build"]

ubuntu18:install:
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu18.04
    siconos_docker_name: siconos-$CI_COMMIT_REF_NAME-ubuntu-bionic
  extends: .siconos-install
  needs: ["ubuntu18.04:full"]

# ubuntu18.04:
#   stage: configure
#   trigger:
#     include:
#       - ci_gitlab/ubuntu.yml

# debianbuster:
#   stage: configure
#   trigger:
#     include:
#       - ci_gitlab/debianbuster.yml
