# Templates for ci jobs
include: ci_gitlab/gitlab-ci-siconos-templates.yml

 
# ---- Docker build jobs -----

# This job create a docker image with all required dependencies
# (including serialization, python wrapper, bullet but not OCE)
# It's based on ubuntu 18.04.
# It uses tag 'docker-build' to enforce run on a dedicated runner.
docker-build:ubuntu18.04:
  variables:
    IMAGE_NAME: ubuntu18.04
  stage: docker-build-layer2
  extends: .docker-build
  dependencies:
    - docker-build:ubuntu18.04-no-python



# ---- Siconos build jobs -----

# Siconos build and install, default config
# (based on cmake/default_siconos.cmake)
# on ubuntu 18.04.
install_siconos:ubuntu18.04:
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/ubuntu18.04
    cdash_submit: 1
    user_file: $CI_PROJECT_DIR/$siconos_confs/siconos_default.cmake
  extends: .siconos-build
  artifacts:
    paths:
      - build

     

# --- Creates a new pipeline to build documentation
# Trigger : manual.
# When the job is activated (manual trigger through the web interface),
# it starts a new pipeline, i.e. includes jobs declared in docs/build-doc.yml
siconos:build-doc:
  stage: build
  trigger:
    include:
      - docs/build-doc.yml
  when: manual


